// Test-only fixture helper (not a .test.ts file, so it's not itself run as
// a test suite — imported by tests that need a realistic BookingRecord).
import type { BookingRecord } from "./types";

export function sampleBookingRecord(overrides: Partial<BookingRecord> = {}): BookingRecord {
  return {
    bookingId: "BELA-20260101-ABCDEF",
    submittedAt: "2026-01-01T12:00:00.000Z",
    bookingStatus: "Pending Payment",
    paymentStatus: "Unpaid",
    firstName: "Jane",
    lastName: "Doe",
    email: "jane@example.com",
    mobile: "5551234567",
    streetAddress: "123 Main St",
    apartmentOrUnit: "",
    city: "Hoboken",
    state: "New Jersey",
    zipCode: "07030",
    someoneHome: "Yes, someone will be home",
    serviceDate: "2026-02-15",
    arrivalWindow: "Morning",
    propertyType: "Apartment",
    squareFootage: "1,001–2,000 sq. ft.",
    bedrooms: "2 bedrooms",
    bathrooms: "2 bathrooms",
    cleaningType: "Standard cleaning",
    extras: "kitchenCabinets;interiorWindows:2",
    frequency: "Weekly",
    baseCleaningPrice: 130,
    bathroomPrice: 20,
    cleaningTypePrice: 0,
    extrasPrice: 60,
    subtotal: 210,
    frequencyDiscount: 19.5,
    totalPrice: 190.5,
    estimatedDurationMinutes: 270,
    specialInstructions: "Please use the side entrance.",
    policyAccepted: true,
    submissionSource: "Website",
    stripeCheckoutSessionId: "",
    stripePaymentIntentId: "",
    paidAt: "",
    cancelledAt: "",
    completedAt: "",
    internalNotes: "idempotency_token:test-token",
    schemaVersion: 1,
    customerConfirmationStatus: "",
    internalNotificationStatus: "",
    notificationAttemptAt: "",
    ...overrides,
  };
}
